import { 
  LayoutDashboard, 
  Target, 
  FileText, 
  Home, 
  Globe, 
  Moon, 
  UserCircle,
  Download,
  PlusCircle,
  Search,
  ChevronLeft,
  ChevronRight,
  Utensils,
  Car,
  Grid,
  TrendingDown,
  AlertTriangle,
  Lightbulb,
  CheckCircle2,
  ShieldCheck,
  CloudUpload,
  X,
  Store,
  CreditCard,
  ShoppingBag,
  History,
  ArrowUpRight,
  Trash2,
  Edit2,
  Smartphone,
  Shield,
  Lock,
  Cloud
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Metas: Target,
  Planilha: FileText,
  Inicio: Home,
  Language: Globe,
  DarkMode: Moon,
  Account: UserCircle,
  Download: Download,
  Add: PlusCircle,
  Search: Search,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Alimentacao: Utensils,
  Transporte: Car,
  Outros: Grid,
  TrendingDown: TrendingDown,
  Warning: AlertTriangle,
  Lightbulb: Lightbulb,
  Check: CheckCircle2,
  Verified: ShieldCheck,
  Upload: CloudUpload,
  Close: X,
  Store: Store,
  Payment: CreditCard,
  ShoppingBag: ShoppingBag,
  History: History,
  ArrowUpRight: ArrowUpRight,
  Trash: Trash2,
  Edit: Edit2,
  Mobile: Smartphone,
  Security: Shield,
  Privacy: Lock,
  Cloud: Cloud
};
